apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
 	path('Noticia/<int:noticia_pk>/comentario/<int:pk>/borrar/', views.Borrar_Comentario.as_view(), name='borrarcomentario'),
    
	path('Editar/<int:pk>', views.Editar_Noticia.as_view(), name = 'editar'),
 
 	path('Agregar/', views.Agregar_Noticia.as_view(), name = 'agregar'),
  	path('Borrar/<int:pk>', views.Borrar_Noticia.as_view(), name = 'borrar'),
  
  	path('Categoria/', views.Listar_Categoria.as_view(), name = 'categoria'),
   	path('Categoria/Agregar', views.Agregar_Categoria.as_view(), name = 'agregarcategoria'),
    path('Categoria/Editar/<int:pk>', views.Editar_Categoria.as_view(), name = 'editarcategoria'),
    path('Categoria/Borrar/<int:pk>', views.Borrar_Categoria.as_view(), name = 'borrarcategoria'),
	
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth
from apps.usuarios.views import LoginUsuario

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    #No necesariamente estos 3 valores (parametors) se deben llamar igual
    path('Nosotros/', views.Nosotros, name = 'nosotros'),

    #LOGIN
    path('login/',LoginUsuario.as_view(),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
    path('Contacto/',include('apps.contacto.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario
from ckeditor.fields import RichTextField

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):

	titulo = models.CharField(max_length = 150, verbose_name='Título')
	#cuerpo = models.TextField(verbose_name='Texto de la noticia')
	cuerpo = RichTextField(verbose_name='Texto de la noticia')
	imagen = models.ImageField(upload_to = 'noticias', default='img-defecto.png', verbose_name='Imagen')
	categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)
	autor = models.ForeignKey(Usuario, on_delete = models.CASCADE, default=1)

	def __str__(self):
		return self.titulo

class Comentario(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	texto = models.TextField(max_length = 1500)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.noticia}->{self.texto}"

apps/noticias/forms.py
from django import forms
from django.shortcuts import render
from ckeditor.widgets import CKEditorWidget


from .models import Noticia, Categoria


class NoticiaForm(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = ('titulo', 'cuerpo', 'categoria_noticia', 'imagen')
        widgets = {
            'cuerpo': CKEditorWidget(),
            'titulo': forms.TextInput(attrs={'class':'form-control',
                                             'label':'Título'}),
            'categoria_noticia': forms.Select(attrs={'class':'form-control',
                                                     'label':'Categoria'}),
        }
    

#imagen = models.ImageField(upload_to = 'noticias')
#categoria_noticia = forms.ForeignKey(Categoria, on_delete = models.CASCADE)
#fecha = models.DateTimeField(auto_now_add=True)

class FiltrarNoticiaForm(forms.Form):
    ORDEN=[(0,'Sin orden'),(1,'Ascendente'),(2,'Descendente')]
    
    id = forms.ChoiceField(label='Categoria:', required=False,
        widget=forms.Select(attrs={'class':'form-control',
                                   'name': 'id'}))
    fecha_desde= forms.DateField(label='Fecha hasta:', required=False,
        widget=forms.DateInput(attrs={'class': 'form-control',
                                      'type': 'date'}))    
    fecha_hasta= forms.DateField(label='Fecha hasta:', required=False,
        widget=forms.DateInput(attrs={'class': 'form-control',
                                      'type': 'date'}))
    orden_antiguedad = forms.ChoiceField(label='Orden Fecha', choices=ORDEN, initial=2,
        widget=forms.Select(attrs={'class': 'form-control'}))
    orden_alfabetico = forms.ChoiceField(label='Orden Alfabetico', choices=ORDEN,
        widget=forms.Select(attrs={'class': 'form-control'})) 

# Formularios para Categorias

class CategoriaForm(forms.ModelForm):
    nombre = forms.CharField(label='Descripción', required=True)
    
    class Meta:
        model = Categoria
        fields = ['nombre',]

apps/noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required

from .models import Noticia, Categoria, Comentario

from django.urls import reverse_lazy

from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic import ListView
from .forms import NoticiaForm, FiltrarNoticiaForm, CategoriaForm

#@login_required
def Listar_Noticias(request):
	contexto = {}
	lista_categoria = []
	
	if request.GET: ## si hay valores que se mantengan los seleccionados
		form = FiltrarNoticiaForm(request.GET)
	else:
		form = FiltrarNoticiaForm()

	id_categoria = request.GET.get('id',None)
	fecha_desde = request.GET.get('fecha_desde',None)
	fecha_hasta = request.GET.get('fecha_hasta',None)
	ord_fecha = request.GET.get('orden_antiguedad',None)
	ord_alfab = request.GET.get('orden_alfabetico',None)

	if id_categoria:
		n = Noticia.objects.filter(categoria_noticia = id_categoria)
	else:
		n = Noticia.objects.all() #RETORNA UNA LISTA DE OBJETOS
 	
	# Filtrar solo si hay datos seleccionados en las fechas y
	# fecha_hasta es mayor o igual a fecha_desde
	if fecha_desde and fecha_hasta:
		if fecha_hasta >= fecha_desde:
			n = n.filter(fecha__range=[fecha_desde,fecha_hasta])

	ordenf='-'
	ordena=''
 
	if ord_fecha:
		ordenf = '' if ord_fecha == 1 else '-'

	if ord_alfab:
		ordena = '' if ord_alfab == 1 else '-'
	
	## si selecciona los dos tipos de orden los ordena primero fecha y luego por titulo
	if ord_fecha and ord_alfab:
		n = n.order_by(ordenf+'fecha',ordena+'titulo')
	elif ord_fecha: ## Si solo es orden por fecha
		n = n.order_by(ordenf+'fecha')
	elif ord_alfab: ## Si solo es orden alfabetico
		n = n.order_by(ordena+'titulo')
	else:
		n = n.order_by(ordenf+'fecha')
 
	cat = Categoria.objects.all().order_by('nombre')

	# Para el filtro por categorias
	lista_categoria.append(('','Todas las categorias'))
	
	for x in cat:
		lista_categoria.append((x.pk,x.nombre))			
     
	form.fields['id'].choices=lista_categoria
	
	contexto['noticias'] = n
	contexto['filtro_form']=form 

	return render(request, 'noticias/listar.html', contexto)

@login_required
def Detalle_Noticias(request, pk):
	contexto = {}

	n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBEJTO
	contexto['noticia'] = n

	c = Comentario.objects.filter(noticia = n)
	contexto['comentarios'] = c

	return render(request, 'noticias/detalle.html',contexto)


@login_required
def Comentar_Noticia(request):

	com = request.POST.get('comentario',None)
	usu = request.user
	noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
	noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
	coment = Comentario.objects.create(usuario = usu, noticia = noticia, texto = com)

	return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': noti}))

class Agregar_Noticia(CreateView):
	model=Noticia
	form_class = NoticiaForm
	success_url= reverse_lazy('noticias:listar')
	template_name= 'noticias/editar_agregar.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['titulo']='AGREGAR NOTICIA'
		return context
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		noticia.save()
		return super().form_valid(form)

class Editar_Noticia(UpdateView):
	model=Noticia
	form_class = NoticiaForm
	success_url= reverse_lazy('noticias:listar')
	template_name= 'noticias/editar_agregar.html'
 
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['titulo']='EDITAR NOTICIA'
		return context

class Borrar_Noticia(DeleteView):
	model = Noticia
	template_name='noticias/confirmar_borrar.html'
	success_url = reverse_lazy('noticias:listar')
 ## Vistas de Categorias
 
class Listar_Categoria(ListView):
	model=Categoria
	form_class = CategoriaForm
	context_object_name = 'categorias'
	success_url= reverse_lazy('noticias:listarcategoria')
	template_name= 'noticias/listar_categoria.html'
 
	def get_queryset(self):
		cat = Categoria.objects.order_by('nombre')
		return cat


class Agregar_Categoria(CreateView):
	model=Categoria
	form_class = CategoriaForm
	success_url= reverse_lazy('noticias:categoria')
	template_name= 'noticias/editar_agregar_categoria.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['titulo']='AGREGAR LA CATEGORIA'
		return context

class Editar_Categoria(UpdateView):
	model=Categoria
	form_class = CategoriaForm
	success_url= reverse_lazy('noticias:categoria')
	template_name= 'noticias/editar_agregar_categoria.html'
 
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['titulo']='EDITAR LA CATEGORIA'
		return context

class Borrar_Categoria(DeleteView):
	model = Categoria
	template_name='noticias/categoria_confirmar_borrar.html'
	success_url = reverse_lazy('noticias:categoria')

# Vistas de Comentario
class Borrar_Comentario(DeleteView):
	model = Comentario
	template_name='noticias/comentario_confirmar_borrar.html'

	def post(self, request, pk, noticia_pk):
		comentario = get_object_or_404(Comentario, pk=pk, noticia_id=noticia_pk)
		comentario.delete()
		return redirect('noticias:detalle', pk=noticia_pk)
 
#{'nombre':'name', 'apellido':'last name', 'edad':23}
#EN EL TEMPLATE SE RECIBE UNA VARIABLE SEPARADA POR CADA CLAVE VALOR
# nombre
# apellido
# edad

'''
ORM

CLASE.objects.get(pk = ____)
CLASE.objects.filter(campos = ____)
CLASE.objects.all() ---> SELECT * FROM CLASE

'''

templates/noticias/categoria_confirmar_borrar.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
<div class="intro h-10">

</div>

<div class="container">
		<div class="row">
				<div class="col-md-12">
					<div class="section-heading">
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <form method="post">{% csrf_token %}
                            <p>Esta seguro de borrar la categoria "{{ object }}"?</p>
                            <br>
                            <br>
                            <input type="submit" value="Confirmar">
                        </form>
                    </div>
                </div>
        </div>
</div>
{% endblock %}

templates/noticias/comentario_confirmar_borrar.html
<form method="post">{% csrf_token %}
    <p>Esta seguro de borrar el comentario "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirmar">
</form>

templates/noticias/confirmar_borrar.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
<div class="intro h-10">

</div>

<div class="container">
        <br>
        <br>
        <br>
        <br>
        <div class="row">
				<div class="col-md-12">
					<div class="section-heading h-20">
                        <form method="post">{% csrf_token %}
                            <h4>Esta seguro de borrar la noticia "{{ object }}"?</h4>
                            {{ form }}
                            <input class="btn btn-primary"type="submit" value="Confirmar">
                        </form>
                    </div>
				</div>
		</div> 
        <br>
        <br>
        <br>
        <br>
        
</div>             
{% endblock %}

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}{% endblock titulo %}


{% block contenido %}
<div class="intro h-10">

</div>
<section class="tabs-content"  id="blog">
		<div class="container">
			<div class="row">
				<div class="text-center section-heading">
					<p>{{noticia.categoria_noticia}}</p>
					<h1>{{noticia.titulo}}</h1>
					<h6 class="my-2 text-muted"> {{noticia.fecha|date:'F jS Y' }}</h6>

					<img class="my-2 img-fluid"src="{{noticia.imagen.url}}" width="500" height="500">
				</div>
				<div class="col-md-12 text-center">
					{{noticia.cuerpo|safe}}
				<div>

			</div>

			<br>

			<!-- Seccion de comentarios -->
			<div class="container">
                 <div class="row">
                    <div class="col-md-12">
                        <form id="contact" method="POST" action="{% url 'noticias:comentar' %}">{% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                  <fieldset>
                                    <textarea name="comentario" rows="6" maxlength="1500" class="form-control" id="message" placeholder="Comentario..." required></textarea>
                                  </fieldset>
                                </div>
                                <div class="col-md-4">
                                  <fieldset>
									<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden=""> 
									<button type="submit" id="form-submit" class="btn">Enviar comentario</button>
                                  </fieldset>
                                </div>
                            </div>
                        </form>
                    </div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="section-heading">
							<h4>Comentarios</h4>
						</div>
					</div>
					<div class="wrapper">
						<div class="tabgroup"">
							{% for com in comentarios %}
							<div class="row">
								<div class="col-md-8">
										<p>{{com.texto}}</p>
									<ul class="info-post">
										<li><i class="fa fa-user"></i>{{com.usuario}}</li>
										<li><i class="fa fa-calendar"></i>{{com.fecha|date}}</li>
									</ul>
								</div>
								<div class="col-md-4">
									{% if user == com.usuario or user.is_superuser%}
										<a class= "botton botton-primary" href="{% url 'noticias:borrarcomentario' noticia_pk=noticia.pk pk=com.pk %}">borrar</a>
									{% endif %}
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
					<br>					
					<a href="{% url 'noticias:listar' %}">VOLVER</a>
				</div>
			</div> <!-- Cierra comentario -->

		</div>
</section>

{% endblock contenido %}

templates/noticias/editar_agregar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}{{titulo}}{% endblock titulo %}


{% block contenido %}
<div class="intro h-10">

</div>
<div class="container">
	<div class="row">
		<div class="text-center section-heading">
			<h4>{{titulo}}</h4>
		</div>
		<div class="col-md-12">
			<div class="text-center">
				<form enctype="multipart/form-data" method="POST">{% csrf_token %}
					<!-- {{form.as_p}} -->
					<div class="col-md-6 form-group">
						<div class="col-md-4">
							{{ form.titulo.label_tag }}
						</div>
						<div class="col-md-8">
							{{ form.titulo }}
						</div>
					</div>
					<div class="col-md-6 form-group">
							<div class="col-md-4">
							{{ form.categoria_noticia.label_tag }}
							</div>
							<div class="col-md-4">
								{{ form.categoria_noticia }}
							</div>
						<div class="col-md6">
							{% if user == noti.autor or user.is_superuser %}
								<a href="{% url 'noticias:agregarcategoria' %}">Agregar Categoria</a>
							{% endif %}
						</div>

					</div>

					<br>
					<div class="col-md-12 form-group">
						<div class="col-md-6">
							{{ form.cuerpo.label_tag }}
						</div>
						<div class="col-md-12">
							{{ form.cuerpo }}
						</div>
					</div>
					<br>
					<br>
					<div class="col-md-12 form-group">
						<div class="col-md-4">
							{{ form.imagen.label_tag }}
						</div>
						<div class="col-md-8">
							{{ form.imagen }}
						</div>
					</div>
					<br>

					<input class="btn btn-primary" type="submit" value="Guardar">
				</form>
				<br>
				<a href="{% url 'noticias:listar' %}">Volver</a>
			</div>
		</div>
	</div>
</div>
		
	
{% endblock contenido %}

templates/noticias/editar_agregar_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}{{titulo}}{% endblock titulo %}


{% block contenido %}
<div class="intro h-10">

</div>

<div class="container">

	<div class="row">

		<div class="text-center section-heading">
			<h4>{{titulo}}</h4>
		</div>
		<br>
		<br>
		<div class="text-center">
		<form enctype="multipart/form-data" method="POST">{% csrf_token %}
            {{form.as_p}}
 
			<input class="btn btn-primary" type="submit" value="Guardar">
		</form>
		<br>
		<br>
		<a href="{% url 'noticias:categoria' %}">Volver</a>
		<br>
		<br>
		</div>
	</div>
</div>
{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}

{% block contenido %}
<div class="intro h-10">

</div>
	<section class="tabs-content" id="blog">
		<div class="container">
			
			<div class="row">
				<form class="col-md-12 section-heading" action="{% url 'noticias:listar' %}" method="get">
					<div class="row">
						<div class="col-md-8 form-group">
							{{ filtro_form.id.label_tag }}
							{{ filtro_form.id }}
						</div>
						<div class="col-md-4 form-group">
							{{ filtro_form.fecha_desde.label_tag }}
							{{ filtro_form.fecha_desde }}
						</div>
						<div class="col-md-4 form-group">
							{{ filtro_form.fecha_hasta.label_tag }}
							{{ filtro_form.fecha_hasta }}
						</div>					
						<div class="col-md-4 form-group">
							{{ filtro_form.orden_antiguedad.label_tag }}
							{{ filtro_form.orden_antiguedad }}
						</div>										
						<div class="col-md-4 form-group">
							{{ filtro_form.orden_alfabetico.label_tag }}
							{{ filtro_form.orden_alfabetico }}
						</div>										
					</div>
					<div class="row">
						<div class="row col-md-6">
							<button class="btn btn-primary my-2 my-sm-0 col-md-2" type="submit">
							Filtrar
							</button>
						</div>
						<div class="row col-md-6">
							{% if user.is_authenticated %}
								<a class="button primary-button" href="{% url 'noticias:agregar' %}">Agregar Noticia</a>
							{% endif %}
						</div>
	
					</div>
				</form>				
			</div>


			<div class="row">
				<div class=" wrapper"></div>
					{% for noti in noticias %}

					<div class="col-md-6">
						<div id="first-tab-group" class="tabgroup">
							<!-- <div id="tab1"> -->
							<div class="card">
								<img src="{{noti.imagen.url}}" alt="">
								<div class="text-content">
									<h4>{{noti.titulo}}</h4>
									<h6><ul class="info-post">
										<li><i class="fa fa-user"></i>{{noti.autor}}</li>
										<li><i class="fa fa-calendar"></i>{{noti.fecha|date}}</li>
											<!-- <li><i class="fa fa-wechat"></i>12 Comments</li> -->
									</ul></h6>
									<p>{{noti.cuerpo|safe|truncatechars:100}}</p>
									<div class="primary-button">
										<a href="{% url 'noticias:detalle' noti.pk   %}">Continue Leyendo
										</a>
									</div>
									<div class="row">
										<div class="col-md-4">
											{% if user == noti.autor or user.is_superuser %}
									 		<a class="button primary-button" href="{% url 'noticias:editar' noti.pk %}">Editar</a>
											{% endif %}
										</div>
										<div class="col-md-4">
											{% if user == noti.autor or user.is_superuser %}
												<a class="button primary-button" href="{% url 'noticias:borrar' noti.pk %}">Borrar</a>
											{% endif %}							
										</div>
									</div>
								</div>
							</div>
							<!-- </div> -->
						</div>
					</div>
					{% endfor %}
				</div>
			</div>

		 </div> <!--Container -->

	</section>
	
{% endblock contenido %}

templates/noticias/listar_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}CATEGORIAS{% endblock titulo %}


{% block contenido %}
<div class="intro h-10">

</div>

<div class="container">

	<div class="row">

		<div class="text-center section-heading">
			<h4>Lista de Categorias</h4>
		</div>
		<br>
		<br>
		<div class="text-center">

            <div class="submenu">
                {% if perms.noticia.add_categoria %}
                    <div class="col-md-6">
                    <a class="btn btn-primary" href="{% url 'noticias:agregarcategoria' %}">Agregar Categoria</a>
                    </div>
                    <div class="col-md-6">
                        <a href="{% url 'noticias:listar' %}">Volver</a>
                    </div>
                {% endif %}

            </div>
        </div>
            <br>
        <br>
        <br>
        <br>
        <div class="row">
            {% for cat in categorias %}
                <div class="col-md-8">
                    <p> {{cat.nombre}}</p>
                </div>
                <div class="col-md-4">

                    {% if perms.noticia.update_categoria %}
                    <div class="col-md-6">
                        <a href="{% url 'noticias:editarcategoria' cat.pk %}">Editar</a>
                    </div>
                    {% endif %}
                    {% if perms.noticia.delete_categoria %}
                        <div class="col-md-6">
                            <a href="{% url 'noticias:borrarcategoria' cat.pk %}">Borrar</a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <br>
        <br>
        <br>
    </div>
</div>
            
{% endblock contenido %}