apps/contacto/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactoView

app_name = 'contacto'

urlpatterns = [
    path('', ContactoView.as_view(), name='contacto'),
    path('gracias/', TemplateView.as_view(template_name='contacto/gracias.html'), name='gracias'),
]

apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
 	path('Noticia/<int:noticia_pk>/comentario/<int:pk>/borrar/', views.Borrar_Comentario.as_view(), name='borrarcomentario'),
    
	path('Editar/<int:pk>', views.Editar_Noticia.as_view(), name = 'editar'),
 
 	path('Agregar/', views.Agregar_Noticia.as_view(), name = 'agregar'),
  	path('Borrar/<int:pk>', views.Borrar_Noticia.as_view(), name = 'borrar'),
  
  	path('Categoria/', views.Listar_Categoria.as_view(), name = 'categoria'),
   	path('Categoria/Agregar', views.Agregar_Categoria.as_view(), name = 'agregarcategoria'),
    path('Categoria/Editar/<int:pk>', views.Editar_Categoria.as_view(), name = 'editarcategoria'),
    path('Categoria/Borrar/<int:pk>', views.Borrar_Categoria.as_view(), name = 'borrarcategoria'),
	
]

apps/usuarios/urls.py
from django.urls import path

from . import views
from .views import UsuarioUpdateView, LoginUsuario


app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),
    #path('login/', LoginUsuario.as_view(), name='login'),
    path('editar/', UsuarioUpdateView.as_view(), name='editar'),  
    path('confirmacion/', views.confirmacion, name='perfil_ok'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth
from apps.usuarios.views import LoginUsuario

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    #No necesariamente estos 3 valores (parametors) se deben llamar igual
    path('Nosotros/', views.Nosotros, name = 'nosotros'),

    #LOGIN
    path('login/',LoginUsuario.as_view(),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
    path('Contacto/',include('apps.contacto.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
		<title>MI WEB| {% block titulo %}{% endblock titulo %}</title>
		<meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- 
Power Template 
http://www.templatemo.com/tm-508-power
-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
        
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/font-awesome.css">
        <link rel="stylesheet" href="/static/css/animate.css">
        <link rel="stylesheet" href="/static/css/templatemo_misc.css">
        <link rel="stylesheet" href="/static/css/templatemo_style.css">
        <link rel="stylesheet" href="/static/css/owl-carousel.css">
		
		<script src="/static/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
		<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"> </script>
		<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"> </script>
    </head>

	<body>

		{% include 't_navbar.html' %}

		</div>
			{% block contenido %}
			
			{% endblock contenido %}
		</div>
		
	</body>
	
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-12">
					
						{% now 'Y' as current_year %}
						<p>Copyright &copy; {{ current_year }} WaNoMa <br> 
						El Poder de la Inteligencia Artificial</p>
				</div>
				<div class="col-md-4 col-sm-12">
					<ul class="social-icons">
						<li><a href="#">Facebook</a></li>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Linkedin</a></li>
						<li><a href="#">Instagram</a></li>
					</ul>
				</div>
				<div class="col-md-2 col-md-offset-2 col-sm-12">
					<div class="back-to-top">
						<a href="{% url 'home' %}">
							<i class="fa fa-angle-up"></i>
							Ir a inicio
						</a>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<script src="/static/js/vendor/jquery-1.11.0.min.js"></script>
	<!-- <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.11.0.min.js"><\/script>')</script> -->
	<script src="/static/js/bootstrap.js"></script>
	<script src="/static/js/plugins.js"></script>
	<script src="/static/js/main.js"></script>

	<!-- Google Map -->
	<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script src="/static/js/vendor/jquery.gmap3.min.js"></script>

	<!-- templatemo 406 flex -->

</html>

templates/t_home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}HOME{% endblock titulo %}


{% block contenido %}
	<div class="banner">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="banner-content">
						<h6>Home</h6>
						<h2>El Poder de la Inteligencia Artificial</h2>
						<ul class="buttons">
							<li>
								<div class="primary-button">
									<a href="{% url 'contacto:contacto' %}">Contacto</a>
								</div>
							</li>
							<li>
								<div class="secondary-button">
									<a href="{% url 'noticias:listar' %}">Mas Detalles</a>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="intro">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h4>Diseño Web &amp; Desarrollo por Wanoma</h4>
					<h6>Creamos esta página</h6>
					<div class="border-button"><a href="{% url 'nosotros' %}">Descubre Mas</a></div>
				</div>
			</div>
		</div>
	</div>
{% endblock contenido %}

templates/t_navbar.html
{% load static %}

       <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

        <div class="site-main" id="sTop">
            <div class="site-header">
                <div class="main-header">
                    <div class="container">
                        <div id="menu-wrapper">
                            <div class="row">
                                <nav class="navbar navbar-inverse" role="navigation">
                                    <div class="navbar-header">
                                        <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <a href="{% url 'home' %}" class="navbar-brand">WaNoMa</a>
                                        <div id="main-nav" class="collapse navbar-collapse">
                                            <ul class="menu-first nav navbar-nav" style="margin-right: 20px;">
                                                <li class="{% if '/' == request.path %} active {% endif %}"><a href= "{% url 'home' %}" >Inicio</a></li>
                                                <li class="{% if '/Nosotros/' == request.path %} active {% endif %}"><a href="{% url 'nosotros' %}">Nosotros</a></li>
                                                <li class="{% if '/Noticias/' == request.path %} active {% endif %}"><a href="{% url 'noticias:listar' %}">Ver Noticias</a></li>
                                                <!-- <li><a href="#" class="external" target="_parent" rel="nofollow">External</a></li>  -->
                                                <li class="{% if '/Contacto/' == request.path %} active {% endif %}"><a href="{% url 'contacto:contacto' %}">Contáctanos</a></li>                                 
                                                <li>
                                                    {% if user.is_authenticated %}
                                                    <a href="#">{{user}}</a>
                                                    <a href="{% url 'usuarios:editar' %}">Perfil</a>
                                                    <a href="{% url 'logout' %}">Cerrar sesión</a>
                                                    {% else %}
                                                    <a href="{% url 'login' %}">Iniciar sesión</a>
                                                    <a href="{% url 'usuarios:registro' %}">Registrarse</a>
                                                    {% endif %}
                                                </li>
                                    
                                            </ul>                                    
                                        </div> <!-- /.main-menu -->
                                    </div>
                                </nav>
                            </div> <!-- /.row -->
                        </div> <!-- /#menu-wrapper -->                        
                    </div> <!-- /.container -->
                </div> <!-- /.main-header -->
            </div> <!-- /.site-header -->
        </div> <!-- /.site-main -->       

templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOSOTROS{% endblock titulo %}


{% block contenido %}
<div class="intro h-10">

</div>
<section id="about" class="page-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4">
				<div class="service-item first-service">
					<div class="icon">
						<img src="{% static '/img/mujer1.png' %}" alt="" width="100px" height="100px">
					</div>
					<h4>Hola Soy Noe</h4>
					<p>Una estudiante del Informatorio Chaco Grupo 9 Comisión 4.</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="service-item second-service">
					<div class="icon">
						<img src="{% static '/img/mujer.png' %}" alt="" width="100px" height="100px">
					</div>
					<h4>Hola Soy Wanda</h4>
					<p>Una estudiante del Informatorio Chaco Grupo 9 Comisión 4.</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="service-item third-service">
					<div class="icon">
						<img src="{% static '/img/hombre.png' %}" alt="" width="100px" height="100px">
					</div>
					<h4>Hola Soy Mauro</h4>
					<p>Un estudiante del Informatorio Chaco Grupo 9 Comisión 4.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="second-tabs-content what-we-do">
		<div class="container">	
	<div class="row">
		<div class="col-md-12">
			<div class="section-heading">
				<h4>Quienes Somos</h4>
				<p>Somos un grupo de Estudiantes del Informatorio Chaco, Edición 2024.</p>
				<p>Estamos en la segunda etapa Desarrollo Web</p>
			</div>
		</div>
	</div>
		</div>
	</div>
	
</section>

{% endblock contenido %}